import type { Metadata } from "next";
import { ViewTransition } from "react";
import { parseLyrics } from "@/lib/lyrics";
import { HERO_ART } from "@/components/music/artwork-morph-link";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { getTrackBySlug } from "@/lib/queries";
import { toPlayerTrack } from "@/lib/mappers";
import { getLikedTrackIds } from "@/lib/favorites";
import { PlayButton } from "@/components/player/play-button";
import { LikeButton } from "@/components/music/like-button";
import { DownloadButton } from "@/components/music/download-button";
import { ShareMenu } from "@/components/music/share-menu";
import { StartRadioButton } from "@/components/music/start-radio-button";
import { AddToPlaylistDialog } from "@/components/music/add-to-playlist-dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArtworkTint } from "@/components/music/artwork-tint";
import { SectionHeader } from "@/components/music/section-header";
import { HorizontalScroller } from "@/components/music/horizontal-scroller";
import { MusicCard } from "@/components/music/music-card";
import { formatReleaseDate, formatDuration } from "@/lib/utils";
import { ListMusic } from "lucide-react";
import { JsonLd } from "@/components/seo/json-ld";
import { resolveTrackCoverUrl } from "@/lib/media/entity-images";
import { recommendationService } from "@/lib/recommendations";
import { TermChips, TermLine } from "@/components/discovery/term-links";
import type { TaxonomyKind } from "@/lib/taxonomy";
import { parseStartParam } from "@/lib/share";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const track = await getTrackBySlug(slug);
  if (!track) return {};

  const description = track.description || `${track.title} by ${track.artist.name} on Vibe Banger.`;
  const title = `${track.title} — ${track.artist.name}`;
  const path = `/song/${track.slug}`;

  // The preview image is generated by ./opengraph-image.tsx.
  return {
    title: track.title,
    description,
    alternates: {
      canonical: path,
      // oEmbed discovery: editors that support it turn a pasted link into the player.
      types: { "application/json+oembed": `/api/oembed?url=${encodeURIComponent(`${process.env.NEXT_PUBLIC_SITE_URL || ""}${path}`)}` },
    },
    openGraph: {
      title,
      description,
      url: path,
      siteName: "Vibe Banger",
      type: "music.song",
      duration: track.duration,
      musicians: [`/artist/${track.artist.slug}`],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function SongPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ t?: string | string[] }>;
}) {
  const { slug } = await params;
  const [track, session, query] = await Promise.all([getTrackBySlug(slug), auth(), searchParams]);

  if (!track) notFound();
  // Set when someone shared a moment: "listen from 1:24".
  const startAt = parseStartParam(query.t, track.duration);

  const termsOf = (kind: TaxonomyKind) => track.terms.filter((t) => t.term.kind === kind).map((t) => t.term);
  const genres = termsOf("GENRE");
  const moods = termsOf("MOOD");
  const vocals = termsOf("VOCAL");
  const perfectFor = [...termsOf("ACTIVITY"), ...termsOf("OCCASION")];
  // The summary line under the title: primary genre, lead mood, vocal style.
  const summaryTerms = [genres[0], moods[0], vocals[0]].filter((t): t is NonNullable<typeof t> => !!t);

  const [moreFromArtist, youMayAlsoLike] = await Promise.all([
    db.track.findMany({
      where: { isPublished: true, artistId: track.artistId, id: { not: track.id } },
      take: 8,
      orderBy: { releaseDate: "desc" },
      include: { artist: true, album: true },
    }),
    // Other artists only: "More from this artist" already covers the rest.
    recommendationService.similarTracks(track.id, { limit: 10, excludeArtistId: track.artistId }),
  ]);

  const playerTrack = toPlayerTrack(track, "large");
  const similarQueue = youMayAlsoLike.map((t) => toPlayerTrack(t));
  const artistQueue = moreFromArtist.map((t) => toPlayerTrack(t));
  // Someone arriving from a shared link keeps listening after this song ends,
  // rather than hitting silence.
  const listenQueue = [playerTrack, ...similarQueue];
  const liked = await getLikedTrackIds(session?.user?.id, [track.id]);
  const shareUrl = `${process.env.NEXT_PUBLIC_SITE_URL || ""}/song/${track.slug}`;
  const heroImage = resolveTrackCoverUrl(track, "large");

  return (
    <div className="relative isolate mx-auto max-w-5xl px-4 py-8 sm:px-8">
      <ArtworkTint src={heroImage} />
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "MusicRecording",
          name: track.title,
          byArtist: { "@type": "MusicGroup", name: track.artist.name, url: `${process.env.NEXT_PUBLIC_SITE_URL || ""}/artist/${track.artist.slug}` },
          duration: `PT${track.duration}S`,
          datePublished: track.releaseDate?.toISOString(),
          image: heroImage ?? undefined,
          url: shareUrl,
          inAlbum: track.album
            ? { "@type": "MusicAlbum", name: track.album.title, url: `${process.env.NEXT_PUBLIC_SITE_URL || ""}/album/${track.album.slug}` }
            : undefined,
        }}
      />
      <div className="flex flex-col gap-8 sm:flex-row sm:items-end">
        {/* Sized so the play button is on the first screen of a phone, above the bottom navigation. */}
        {/* The other half of the morph — see components/music/music-card.tsx. */}
        <ViewTransition name={HERO_ART} share="morph" default="none">
          <div className="relative aspect-square w-56 shrink-0 overflow-hidden rounded-xl shadow-elevated sm:w-64">
            {heroImage && (
              <Image src={heroImage} alt={track.title} fill sizes="256px" className="object-cover" priority />
            )}
          </div>
        </ViewTransition>

        <div className="min-w-0 flex-1">
          <p className="text-xs font-medium uppercase tracking-[0.2em] text-foreground-subtle">Song</p>
          <div className="mt-2 flex items-center gap-3">
            <h1 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{track.title}</h1>
            {track.isExplicit && <Badge variant="outline">Explicit</Badge>}
            {/* How the music was made is stated further down, with the other
                facts about the track. An accent badge beside the title
                announced it before anyone had heard a note, which is louder
                than the fact deserves — it belongs where someone goes to
                learn about a song, not in place of the song. */}
          </div>
          <div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-foreground-muted">
            <Link href={`/artist/${track.artist.slug}`} className="font-medium text-foreground hover:underline">
              {track.artist.name}
            </Link>
            {track.album && (
              <>
                <span>·</span>
                <Link href={`/album/${track.album.slug}`} className="hover:underline">
                  {track.album.title}
                </Link>
              </>
            )}
            {/* Both conditional, the way the album above already is. A track
                with no release date drew a separator with nothing after it,
                and one whose processing never recorded a duration showed a
                flat 0:00 as though it were silent. */}
            {track.releaseDate && (
              <>
                <span>·</span>
                <span>{formatReleaseDate(track.releaseDate)}</span>
              </>
            )}
            {track.duration > 0 && (
              <>
                <span>·</span>
                <span className="tabular">{formatDuration(track.duration)}</span>
              </>
            )}
          </div>

          <TermLine terms={summaryTerms} className="mt-2" />

          <div className="mt-5 flex flex-wrap items-center gap-3 sm:mt-6">
            {startAt !== null ? (
              <PlayButton track={playerTrack} queue={listenQueue} startAt={startAt} label={`Play from ${formatDuration(startAt)}`} size="lg" />
            ) : (
              <PlayButton track={playerTrack} queue={listenQueue} size="lg" />
            )}
            <StartRadioButton track={playerTrack} />
            <LikeButton trackId={track.id} initialLiked={liked.has(track.id)} size="lg" className="rounded-full border border-border-strong p-2.5" />
            <DownloadButton track={playerTrack} size="lg" className="rounded-full border border-border-strong p-2.5" />
            <AddToPlaylistDialog
              trackId={track.id}
              trigger={
                <Button variant="outline" size="icon-lg" aria-label="Add to playlist">
                  <ListMusic className="h-5 w-5" />
                </Button>
              }
            />
            <ShareMenu
              url={shareUrl}
              title={track.title}
              text={`${track.title} by ${track.artist.name}`}
              trackId={track.id}
              size="lg"
              className="rounded-full border border-border-strong p-2.5"
            />
          </div>

          {startAt !== null && (
            <p className="mt-3 text-sm text-foreground-muted">
              Shared from <span className="tabular text-foreground">{formatDuration(startAt)}</span> ·{" "}
              <Link href={`/song/${track.slug}`} replace scroll={false} className="text-foreground underline-offset-4 hover:underline">
                Play from the start
              </Link>
            </p>
          )}

          {track.description && <p className="mt-5 max-w-xl text-sm text-foreground-muted">{track.description}</p>}
        </div>
      </div>

      {(moods.length > 0 || perfectFor.length > 0 || genres.length > 0) && (
        <div className="mt-12 grid gap-8 sm:grid-cols-3">
          {genres.length > 0 && (
            <div>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-foreground-subtle">Genre</h2>
              <TermChips terms={genres} />
            </div>
          )}
          {moods.length > 0 && (
            <div>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-foreground-subtle">Mood</h2>
              <TermChips terms={moods} />
            </div>
          )}
          {perfectFor.length > 0 && (
            <div>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-foreground-subtle">Perfect For</h2>
              <TermChips terms={perfectFor} />
            </div>
          )}
        </div>
      )}

      {/* The disclosure counts towards showing this block: a track with no
          lyrics and no credits still has something to say about how it was
          made, and skipping the section would hide it entirely. */}
      {(track.lyrics ||
        track.credits ||
        track.composer ||
        track.producer ||
        track.aiDisclosure !== "HUMAN_CREATED" ||
        track.lyricsAuthor !== "INSTRUMENTAL") && (
        <div className="mt-12 grid gap-8 sm:grid-cols-2">
          {track.lyrics && (
            <div>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-foreground-subtle">Lyrics</h2>
              {/* Words only — any LRC timings belong to the player, not the page. */}
              <p className="whitespace-pre-line text-sm leading-relaxed text-foreground-muted">
                {parseLyrics(track.lyrics).plain}
              </p>
            </div>
          )}
          {(track.credits ||
            track.composer ||
            track.producer ||
            track.aiDisclosure !== "HUMAN_CREATED" ||
            track.lyricsAuthor !== "INSTRUMENTAL") && (
            <div>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-foreground-subtle">Credits</h2>
              <dl className="space-y-1.5 text-sm">
                {/* Still said plainly, and still here for anyone who looks —
                    just stated rather than advertised. Named with the tool
                    when the creator gave one, because "Suno" tells someone
                    more than "AI" does. */}
                {/* Two separate facts, said separately. Who wrote the words
                    is the one listeners ask about, and on this catalogue the
                    answer is usually a person even though the music was
                    produced with AI — which one combined line could never
                    say. */}
                {track.lyricsAuthor !== "INSTRUMENTAL" && (
                  <div className="flex gap-2">
                    <dt className="text-foreground-muted">Words</dt>
                    <dd className="text-foreground">
                      {track.lyricsAuthor === "ARTIST" ? `Written by ${track.artist.name}` : "Written with AI"}
                    </dd>
                  </div>
                )}
                {track.aiDisclosure !== "HUMAN_CREATED" && (
                  <div className="flex gap-2">
                    <dt className="text-foreground-muted">Music</dt>
                    <dd className="text-foreground">
                      {track.aiDisclosure === "AI_ASSISTED" ? "Composed with AI" : "Composed by AI"}
                      {track.aiTool ? ` · ${track.aiTool}` : ""}
                    </dd>
                  </div>
                )}
                {track.composer && (
                  <div className="flex gap-2">
                    <dt className="text-foreground-muted">Composer</dt>
                    <dd className="text-foreground">{track.composer}</dd>
                  </div>
                )}
                {track.producer && (
                  <div className="flex gap-2">
                    <dt className="text-foreground-muted">Producer</dt>
                    <dd className="text-foreground">{track.producer}</dd>
                  </div>
                )}
                {track.credits && <p className="whitespace-pre-line text-foreground-muted">{track.credits}</p>}
              </dl>
            </div>
          )}
        </div>
      )}

      {moreFromArtist.length > 0 && (
        <div className="mt-14">
          <SectionHeader title={`More from ${track.artist.name}`} href={`/artist/${track.artist.slug}`} />
          <HorizontalScroller>
            {artistQueue.map((t) => (
              <MusicCard key={t.id} track={t} queue={artistQueue} />
            ))}
          </HorizontalScroller>
        </div>
      )}

      {youMayAlsoLike.length > 0 && (
        <div className="mt-10">
          <SectionHeader title="You May Also Like" />
          <HorizontalScroller>
            {similarQueue.map((t) => (
              <MusicCard key={t.id} track={t} queue={similarQueue} />
            ))}
          </HorizontalScroller>
        </div>
      )}
    </div>
  );
}
