import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Section, Bullets } from "@/components/legal/legal-page";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy",
  description: "What Vibe Banger collects, why, and how to have it removed.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy"
      intro={`What ${LEGAL.siteName} collects, why we collect it, and how to get rid of it. Written to be read rather than to be survived.`}
    >
      <Section title="What we hold about you">
        <p>Only what the app needs to work:</p>
        <Bullets
          items={[
            <>
              <strong className="text-foreground">Your account</strong> — the name you gave, your email address, and your
              password stored as a hash we cannot reverse.
            </>,
            <>
              <strong className="text-foreground">What you listen to</strong> — plays, listening history, liked songs,
              playlists, saved albums and the creators you follow. This is what makes the library and Continue Listening
              work.
            </>,
            <>
              <strong className="text-foreground">Song requests</strong> — the brief you write when you commission a
              song, and the messages on it.
            </>,
            <>
              <strong className="text-foreground">Uploads, if you publish</strong> — your audio, artwork, the details you
              enter, and a record of when you confirmed you had the rights to it.
            </>,
          ]}
        />
        <p>
          We do not sell any of it, and we do not run advertising or third-party tracking on the site.
        </p>
      </Section>

      <Section title="Listening without an account">
        <p>
          You can listen without signing up. Plays are still counted so creators can see how their music is doing, using
          a random identifier generated by your browser. It is not linked to a name, an email, or anything else about
          you, and it changes if you clear your browser storage.
        </p>
      </Section>

      <Section title="When your request is about someone else">
        <p>
          A song request usually describes another person — their name, what they are to you, how to refer to them, and
          something that happened between you. That person did not sign up here, so we treat it carefully: it is used
          only to write and produce the song you asked for, it is visible only to you and to us, and it is never
          published or used to promote anything.
        </p>
        <p>
          Tell us if you want a request and its messages deleted, and we will remove them. Please only write about
          someone else what you would be comfortable telling them you had written.
        </p>
      </Section>

      <Section title="Music you save for offline">
        <p>
          Downloads are stored by your own browser on your own device. They are not uploaded anywhere, we cannot see
          them, and removing them from the Downloads page removes them completely.
        </p>
      </Section>

      <Section title="Cookies">
        <p>
          One cookie, which keeps you signed in. There are no advertising or analytics cookies. Some preferences —
          volume, crossfade, what was playing — are kept by your browser on your device and never reach us.
        </p>
      </Section>

      <Section title="Who else is involved">
        <p>These services process data on our behalf so the site can function:</p>
        <Bullets
          items={[
            <>
              <strong className="text-foreground">Railway</strong> — runs the application and the database.
            </>,
            <>
              <strong className="text-foreground">Cloudflare R2</strong> — stores and delivers audio files.
            </>,
            <>
              <strong className="text-foreground">Cloudinary</strong> — stores and delivers artwork.
            </>,
            <>
              <strong className="text-foreground">Resend</strong> — sends the emails about your commissions, when email
              is switched on.
            </>,
          ]}
        />
        <p>None of them are given your data for their own purposes.</p>
      </Section>

      <Section title="How long we keep it">
        <p>
          Your account data stays while your account exists. Listening history and play records are kept so the library
          and the charts keep working. Song requests are kept while the commission is live and afterwards as a record of
          what was agreed and paid for.
        </p>
        <p>Ask us to delete any of it and we will.</p>
      </Section>

      <Section title="Getting a copy, or getting it deleted">
        <p>
          You can delete your account yourself, at any time, from your{" "}
          <Link href="/account" className="font-medium text-foreground underline">
            account page
          </Link>
          . It happens immediately.
        </p>
        <p>
          For anything else — a copy of what we hold, or a correction — email{" "}
          <a href={`mailto:${LEGAL.contactEmail}`} className="font-medium text-foreground underline">
            {LEGAL.contactEmail}
          </a>{" "}
          from the address on your account and ask. We will do it and confirm when it is done.
        </p>
        <p>
          Deleting removes your profile, playlists, likes, history, downloads, follows and requests. Music you published
          comes off the site; the recordings stay in our storage until we remove them, so tell us if you want them
          destroyed too. Play counts stay with the creators you listened to, carrying nothing that identifies you.
        </p>
      </Section>

      <Section title="Children">
        <p>
          This is not a service for children. Do not create an account if you are under 13, or under the age at which
          you can agree to this yourself where you live.
        </p>
      </Section>

      <Section title="Changes">
        <p>
          If this changes in a way that matters, the date at the top changes and we will say so on the site. Carrying on
          using {LEGAL.siteName} after that means the new version applies.
        </p>
      </Section>

      <Section title="Asking us anything">
        <p>
          Write to{" "}
          <a href={`mailto:${LEGAL.contactEmail}`} className="font-medium text-foreground underline">
            {LEGAL.contactEmail}
          </a>
          , or use the <Link href="/contact" className="font-medium text-foreground underline">contact page</Link>. A
          person reads it.
        </p>
      </Section>
    </LegalPage>
  );
}
