/**
 * Photography bundled with the app for discovery categories, so every genre,
 * mood, activity and occasion has a real image from the first visit — before
 * any track has been tagged and before an admin has uploaded artwork.
 *
 * All of it is public domain (CC0 or the public domain mark) and needs no
 * attribution; provenance is recorded in public/categories/credits.json.
 *
 * Generated by scripts/category-photos.mjs — edit that, not this.
 */
import type { TaxonomyKind } from "@/lib/generated/prisma/client";

const PHOTOS: Record<string, string> = {
  "ACTIVITY:coding": "activity-coding.jpg",
  "ACTIVITY:deep-focus": "activity-deep-focus.jpg",
  "ACTIVITY:deep-sleep": "activity-deep-sleep.jpg",
  "ACTIVITY:exam-preparation": "activity-exam-preparation.jpg",
  "ACTIVITY:falling-asleep": "activity-falling-asleep.jpg",
  "ACTIVITY:focus": "activity-focus.jpg",
  "ACTIVITY:lo-fi-study": "activity-lo-fi-study.jpg",
  "ACTIVITY:long-sleep-sessions": "activity-long-sleep-sessions.jpg",
  "ACTIVITY:meditation": "activity-meditation.jpg",
  "ACTIVITY:rain-and-nature": "activity-rain-and-nature.jpg",
  "ACTIVITY:reading": "activity-reading.jpg",
  "ACTIVITY:relaxation": "activity-relaxation.jpg",
  "ACTIVITY:running": "activity-running.jpg",
  "ACTIVITY:sleep": "activity-sleep.jpg",
  "ACTIVITY:study": "activity-study.jpg",
  "ACTIVITY:travel": "activity-travel.jpg",
  "ACTIVITY:work": "activity-work.jpg",
  "ACTIVITY:workout": "activity-workout.jpg",
  "ACTIVITY:yoga": "activity-yoga.jpg",
  "GENRE:afrobeat": "genre-afrobeat.jpg",
  "GENRE:ambient": "genre-ambient.jpg",
  "GENRE:cinematic": "genre-cinematic.jpg",
  "GENRE:classical": "genre-classical.jpg",
  "GENRE:electronic": "genre-electronic.jpg",
  "GENRE:highlife": "genre-highlife.jpg",
  "GENRE:hip-hop": "genre-hip-hop.jpg",
  "GENRE:jazz": "genre-jazz.jpg",
  "GENRE:lo-fi": "genre-lo-fi.jpg",
  "GENRE:pop": "genre-pop.jpg",
  "GENRE:randb": "genre-randb.jpg",
  "GENRE:reggae": "genre-reggae.jpg",
  "GENRE:rock": "genre-rock.jpg",
  "GENRE:soul": "genre-soul.jpg",
  "GENRE:world": "genre-world.jpg",
  "MOOD:calm": "mood-calm.jpg",
  "MOOD:chill": "mood-chill.jpg",
  "MOOD:dark": "mood-dark.jpg",
  "MOOD:dreamy": "mood-dreamy.jpg",
  "MOOD:energetic": "mood-energetic.jpg",
  "MOOD:epic": "mood-epic.jpg",
  "MOOD:happy": "mood-happy.jpg",
  "MOOD:melancholic": "mood-melancholic.jpg",
  "MOOD:motivational": "mood-motivational.jpg",
  "MOOD:nostalgic": "mood-nostalgic.jpg",
  "MOOD:peaceful": "mood-peaceful.jpg",
  "MOOD:romantic": "mood-romantic.jpg",
  "MOOD:uplifting": "mood-uplifting.jpg",
  "OCCASION:african-wedding": "occasion-african-wedding.jpg",
  "OCCASION:afro-romantic": "occasion-afro-romantic.jpg",
  "OCCASION:afrobeat-wedding": "occasion-afrobeat-wedding.jpg",
  "OCCASION:birthday": "occasion-birthday.jpg",
  "OCCASION:bride-entrance": "occasion-bride-entrance.jpg",
  "OCCASION:celebration": "occasion-celebration.jpg",
  "OCCASION:ceremony": "occasion-ceremony.jpg",
  "OCCASION:dance-floor": "occasion-dance-floor.jpg",
  "OCCASION:dinner": "occasion-dinner.jpg",
  "OCCASION:first-dance": "occasion-first-dance.jpg",
  "OCCASION:groom-entrance": "occasion-groom-entrance.jpg",
  "OCCASION:highlife-wedding": "occasion-highlife-wedding.jpg",
  "OCCASION:memorial": "occasion-memorial.jpg",
  "OCCASION:party": "occasion-party.jpg",
  "OCCASION:processional": "occasion-processional.jpg",
  "OCCASION:recessional": "occasion-recessional.jpg",
  "OCCASION:road-trip": "occasion-road-trip.jpg",
  "OCCASION:romantic-evening": "occasion-romantic-evening.jpg",
  "OCCASION:vows": "occasion-vows.jpg",
  "OCCASION:wedding": "occasion-wedding.jpg",
  "OCCASION:wedding-celebration": "occasion-wedding-celebration.jpg",
  "OCCASION:wedding-ceremony": "occasion-wedding-ceremony.jpg",
  "OCCASION:wedding-closing": "occasion-wedding-closing.jpg",
  "OCCASION:wedding-dinner": "occasion-wedding-dinner.jpg",
  "OCCASION:wedding-reception": "occasion-wedding-reception.jpg",
};

/** The bundled photo for a category, or null where none was curated. */
export function categoryPhoto(kind: TaxonomyKind, slug: string): string | null {
  const file = PHOTOS[`${kind}:${slug}`];
  return file ? `/categories/${file}` : null;
}

/**
 * The bundled photo for whichever category goes by this slug, for things
 * named after a category without being one — an editorial playlist called
 * "Deep Focus", say. Exact matches only, so a photo only ever stands in for
 * the thing it depicts.
 */
export function categoryPhotoForSlug(slug: string): string | null {
  const match = Object.keys(PHOTOS).find((key) => key.endsWith(`:${slug}`));
  return match ? `/categories/${PHOTOS[match]}` : null;
}

/**
 * The photo for a stored "KIND:slug" key, as tracks carry in artworkCategory.
 * Unknown keys resolve to null, so a renamed or retired category degrades to
 * no artwork rather than a broken image.
 */
export function categoryPhotoForKey(key: string | null | undefined): string | null {
  if (!key) return null;
  const file = PHOTOS[key];
  return file ? `/categories/${file}` : null;
}
